"""create states table

Revision ID: 01ad991fe2f9
Revises: 
Create Date: 2025-10-25 22:58:38.826316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01ad991fe2f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('states',
    sa.Column('state_name', sa.String(length=50), nullable=False),
    sa.Column('ocd_id', sa.String(length=100), nullable=True),
    sa.Column('fips_code', sa.String(length=2), nullable=True),
    sa.PrimaryKeyConstraint('state_name'),
    sa.UniqueConstraint('fips_code'),
    sa.UniqueConstraint('ocd_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('states')
    # ### end Alembic commands ###
