"""change nullable on sources table

Revision ID: f803498db830
Revises: 261d4a0f518d
Create Date: 2025-10-26 12:10:43.704356

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f803498db830'
down_revision = '261d4a0f518d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.alter_column('body_id',
               existing_type=sa.UUID(),
               nullable=True)
        batch_op.alter_column('source_type',
               existing_type=postgresql.ENUM('council_file', 'bill', 'agenda', 'minutes', 'vote_roll', 'executive_order', 'press_release', 'report', 'budget', 'lawsuit_docket', 'election_notice', name='source_type'),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.alter_column('source_type',
               existing_type=postgresql.ENUM('council_file', 'bill', 'agenda', 'minutes', 'vote_roll', 'executive_order', 'press_release', 'report', 'budget', 'lawsuit_docket', 'election_notice', name='source_type'),
               nullable=False)
        batch_op.alter_column('body_id',
               existing_type=sa.UUID(),
               nullable=False)

    # ### end Alembic commands ###
